<a href="https://colab.research.google.com/github/mallapureddykumith/100-days-data-analytics-learning-journey/blob/main/Copy_of_data_analtics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
num = (2,3)
print(num)

(2, 3)

In [ ]:
import pandas as pd
print("pandasimported")

pandasimported

In [ ]:
#creating series
data = [1,2,3,4]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
data = [1,2,3,4,5]
i= ['a','b','e','c','d']
s = pd.Series(data, index = i)
print(s)

a    1
b    2
e    3
c    4
d    5
dtype: int64

In [ ]:
#creating a series from dictionary
s2 = pd.Series({'x': 100, 'y': 200,'z': 300})
print(s2)

x    100
y    200
z    300
dtype: int64

In [ ]:
#accessing elements
print(s2[0])
print(s2[0:2])
print(s2[1:])
print(s2[:2])

100
x    100
y    200
dtype: int64
y    200
z    300
dtype: int64
x    100
y    200
dtype: int64

/tmp/ipykernel_1150/4019448474.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[0])

In [ ]:
#positin based index
print(s2[0])
print(s2[0:2])
print(s2[1:])
print(s2[:2])
print(s2[2])

100
x    100
y    200
dtype: int64
y    200
z    300
dtype: int64
x    100
y    200
dtype: int64
300

/tmp/ipykernel_1150/2129659081.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[0])
/tmp/ipykernel_1150/2129659081.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[2])

In [ ]:
data = [1,2,3,4,5]
i= ['a','b','e','c','d']
s = pd.Series(data, index = i)
print(s)
#updating
s['a']= 10
print(s)
s['c']= 30
print(s)
#inserting new data(directly/concat)
s['f']= 80
print(s)
#remove(drop method)
s = s.drop("a")
print(s)

a    1
b    2
e    3
c    4
d    5
dtype: int64
a    10
b     2
e     3
c     4
d     5
dtype: int64
a    10
b     2
e     3
c    30
d     5
dtype: int64
a    10
b     2
e     3
c    30
d     5
f    80
dtype: int64
b     2
e     3
c    30
d     5
f    80
dtype: int64

In [ ]:
import pandas as pd
marks=['78','85','92','67','88']
students_id = [101, 102 ,103, 104, 105]
s= pd.Series(marks,index=students_id)
print(s)
print(s[2])

101    78
102    85
103    92
104    67
105    88
dtype: object

KeyError: 2

In [ ]:
#creating series
import pandas as pd
s = pd.Series(
    [5000, 7000, 6000, 9000, 8000],
    index=["Monday", "Tuesday", "Wednesday", "Thursday", "friday"]
)
print(s)
#head-displays the 1st  5 rows
s.head()
s.head(1)
s.head(3)
#tail
s.tail()
s.tail(3)
len(s)
#returns the number of elements and comma indicates that series is one-dimentional
s.shape
#shows the index
s.index
#shows the only values
s.values
#selecting using index
s["Monday"]
#multipule
s[["Monday", "Wednesday"]]
#filtering using a condition(boolean condition)
s > 6000
#conditions
s[s > 6000]
#cleaning data
#missing values(NaN-NOT A NUMBER)
s = pd.Series([5000, 7000, None, 9000, None])
print(s)
#finding missing values
s.isna()
#count of missing values
s.isna().sum()
#fillna(0)
s.fillna(1)
#dropna()removes missing values
s.dropna()
#manupulation
#replacing  values
#(for the perminent cause we need to use s = s.)
s = s.replace(5000, 5550)
print(s)

Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
friday       8000
dtype: int64
0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64
0    5550.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

In [ ]:
import pandas as pd
#creating a data frame
#pd.DataFrame(data)
data = [
    ["ravi", 22, 30000],
    ["priya", 5, 40000],
    ["ethan", 77, 50000]
]
df = pd.DataFrame(data)
print(df)

       0   1      2
0   Ravi  22  30000
1  Priya   5  40000
2  ethan  77  50000

In [ ]:
#tuple
import pandas as pd
#creating a data frame
#pd.DataFrame(data)
data = (
    ("julie", 22, 30000),
    ("thabitha", 5, 40000),
    ("ethan", 77, 50000)
)
df = pd.DataFrame(data)
print(df)

          0   1      2
0     julie  22  30000
1  thabitha   5  40000
2     ethan  77  50000

In [ ]:
#set
my_set = {100, 200, 300, 400}
df_from_set = pd.DataFrame(
    list(my_set),
    #column=['values']
)
print(df_from_set)

     0
0  200
1  100
2  400
3  300

In [ ]:
#dictionarykey -column name
data = {
    'name':['alice', 'dora', 'julie'],
    'age':[10,20,30],
    'city':['ny', 'la' ,'chicago']
}
df = pd.DataFrame(data)
print(df)

    name  age     city
0  alice   10       ny
1   dora   20       la
2  julie   30  chicago

In [ ]:
#series to dataframe (to_frame)
s = pd.Series(
    [1, 2, 3, 4],
    name='Numbers'
)
df = s.to_frame()
print(df)

   Numbers
0        1
1        2
2        3
3        4

In [ ]:
s = pd.Series(
    [1, 2, 3, 4],

s2 = pd.Series
    [9, 8, 8, 9],
s3 = pd.Series
    [12, 13, 14, 15],
)
df = s.to_frame(s,s2,s3),
print(df)

TypeError: type 'Series' is not subscriptable

In [ ]:
#iloc means integer based allocation
import pandas as pd
s = pd.Series(
    [5000, 7000, 6000, 9000, 8000],
    index=["Monday", "Tuesday", "Wednesday", "Thursday", "friday"]
)
print(s)
s.iloc[0:3]
s.loc["Monday"]
s.mean()
s.median()
s.sum()
s.max()
s.min()
s.count()
s.sum()

Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
friday       8000
dtype: int64

np.int64(35000)

In [ ]:
import pandas as pd
data = {
    "Name":["Ravi", "priya", "Arun", "Sneha", "kiran", "Anjali", "Vikram", "Meena"],
    "Age":[22, 24, None, 25, None, 26, 20, 27],
    "city":["Hyderabad", "Chennai", "Bangalore", "Hyderabad",
            "Mumbai", None, "Bangalore", "Mumbai"],
    "Salary":[30000, 40000, 28000, 50000, 35000, 45000, None, 55000]

}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame(data,index=i)
print(df)
df.iloc[0:3]
df.loc[101]
df.loc[101:103]

       Name   Age       city   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   priya  24.0    Chennai  40000.0
103    Arun   NaN  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  Vikram  20.0  Bangalore      NaN
108   Meena  27.0     Mumbai  55000.0

      Name   Age       city   Salary
101   Ravi  22.0  Hyderabad  30000.0
102  priya  24.0    Chennai  40000.0
103   Arun   NaN  Bangalore  28000.0

In [ ]:
import pandas as pd
data = {
    "Name":["Ravi", "priya", "Arun", "Sneha", "kiran", "Anjali", "Vikram", "Meena"],
    "Age":[22, 24, None, 25, None, 26, 20, 27],
    "city":["Hyderabad", "Chennai", "Bangalore", "Hyderabad",
            "Mumbai", None, "Bangalore", "Mumbai"],
    "Salary":[30000, 40000, 28000, 50000, 35000, 45000, None, 55000]

}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame(data,index=i)
print(df)
df.iloc[0:3]
df.loc[101]
df.loc[101:103]
df.mean()
df.median()
df.sum()
df.max()
df.min()
df.count()
df.sum()

In [ ]:
#concat is used only for series
s1 = pd.Series([100,200,300])
s2 = pd.Series([400,500,600])
print(s1)
print(s2)
r = pd.concat([s1,s2],ignore_index=True)
print(r)

0    100
1    200
2    300
dtype: int64
0    400
1    500
2    600
dtype: int64
0    100
1    200
2    300
3    400
4    500
5    600
dtype: int64

In [ ]:
#merge is primarily a dataframe opertaion
import pandas as pd
data = [50000,90000,8900,9878,3999,98778,8789,9876,None,78900]
i=['Aug-01','Aug-02','Aug-03','Aug-04','Aug-05','Aug-06','Aug-07','Aug-08','Aug-09','Aug-10']
s = pd.Series(data,index=i)
print(s)
s.head(5)
s.tail(3)
s.isna()
s.fillna(1000)
s>35000
s.replace(8900,34000)
s.drop("Aug-04")
s.add(50000)
s.max()
s.min()
s.mean()
s.median()

Aug-01    50000.0
Aug-02    90000.0
Aug-03     8900.0
Aug-04     9878.0
Aug-05     3999.0
Aug-06    98778.0
Aug-07     8789.0
Aug-08     9876.0
Aug-09        NaN
Aug-10    78900.0
dtype: float64

9878.0

In [ ]:
import pandas as pd
data = [120000,135000,None,150000,165000,None,180000,195000,210000,225000]
months = ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october']
s = pd.Series(data, index=months)
print(s)
s.head(5)
s.tail(3)
print(s[['january','march','may']])
s>170000
s.isna()
s.isna().sum()
s.fillna
s.sum()
s.mean()
s.max()
s.min()

january      120000.0
february     135000.0
march             NaN
april        150000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
dtype: float64
january    120000.0
march           NaN
may        165000.0
dtype: float64

120000.0

In [ ]:
#converting a series into dataframe
import pandas as pd
s = pd.Series(
    [1, 2, 3, 4],
    name='Numbers'
)
s2 = pd.Series([9, 8, 8, 9])
s3 = pd.Series([12, 13, 14, 15])
df = s.to_frame()
d= {
"name" :s,
"age" : s2,
"marks" : s3}
df = pd.DataFrame(d)

print(df)

   name  age  marks
0     1    9     12
1     2    8     13
2     3    8     14
3     4    9     15

In [ ]:
#renaming the single column
s = pd.Series(
    [1, 2, 3, 4],
)
df = s.to_frame()
df.columns = ['Digits']
print(df)

   Digits
0       1
1       2
2       3
3       4

In [ ]:
#renaming existing columns(allows us to change selected columns without changing the remaining)
df.rename(
    columns={
        'A' : 'Alpha',
        'B' : 'Beta'
    },
    inplace= True
)
print(df)

   Digits
0       1
1       2
2       3
3       4

In [ ]:
s = pd.Series(
    [1, 2, 3, 4],
)
df = s.to_frame()
df.columns = ['Digits']
print(df)
df.head()
df.tail()
df.shape
df.info()
#info() provides imp structural information about dataframe , such as columns names, data types)
df.describe()
#describe()-provides statistical information such as count, mean, standard deviation, min and max for numerical columns
df['Digits']
#step-4-selecting and filtering data
#select a single column --by using column nmae inside square brackets[]

df.iloc[3]
#iloc-is used to selecting the rows
#while loc is used to index
df.loc[3]

NameError: name 'pd' is not defined

In [38]:
import pandas as pd
data = {
    "Name":["Ravi", "priya", "Arun", "Sneha", "kiran", "Anjali", "Vikram", "Meena"],
    "Age":[22, 24, None, 25, None, 26, 20, 27],
    "city":["Hyderabad", "Chennai", "Bangalore", "Hyderabad",
            "Mumbai", None, "Bangalore", "Mumbai"],
    "Salary":[30000, 40000, 28000, 50000, 35000, 45000, None, 55000]

}
df = pd.DataFrame(data)
print(df)
df.iloc[0]
print("_____________________________________")
e = df["Age"]>21
print(e)
print("_____________________________________")
d=df[df["Age"]>21]
print(d)
#df-boolean values which is true or false
#df[df["f"]]
f=df[df["Salary"]>40000]
print(f)
print("_____________________________________")
g=df[df["city"]=="Hyderabad"]
print(g)
k=df[(df["Age"]>22) &(df["city"]=='Hyderabad')]
print(k)
print("_____________________________________")
h=df[
    (df["Salary"]>45000)|
 (df["city"]=='Mumbai')
 ]
print(h)
df.isna()
df.isna().sum()
df.dropna()
df.dropna(axis=0)
df.dropna(how='all')
print("_____________________________________")
df.dropna(axis=0,inplace=True)
print(df)
#filling with different kinds of values
df.fillna({
    'Age':0,
    'Salary':'700000'
})
print(df)
df['Age'] == df['Age'].fillna(
    df['Age'].mean())

     Name   Age       city   Salary
0    Ravi  22.0  Hyderabad  30000.0
1   priya  24.0    Chennai  40000.0
2    Arun   NaN  Bangalore  28000.0
3   Sneha  25.0  Hyderabad  50000.0
4   kiran   NaN     Mumbai  35000.0
5  Anjali  26.0       None  45000.0
6  Vikram  20.0  Bangalore      NaN
7   Meena  27.0     Mumbai  55000.0
_____________________________________
0     True
1     True
2    False
3     True
4    False
5     True
6    False
7     True
Name: Age, dtype: bool
_____________________________________
     Name   Age       city   Salary
0    Ravi  22.0  Hyderabad  30000.0
1   priya  24.0    Chennai  40000.0
3   Sneha  25.0  Hyderabad  50000.0
5  Anjali  26.0       None  45000.0
7   Meena  27.0     Mumbai  55000.0
     Name   Age       city   Salary
3   Sneha  25.0  Hyderabad  50000.0
5  Anjali  26.0       None  45000.0
7   Meena  27.0     Mumbai  55000.0
_____________________________________
    Name   Age       city   Salary
0   Ravi  22.0  Hyderabad  30000.0
3  Sneha  25.0  Hyderabad  50000.0
    Name   Age       city   Salary
3  Sneha  25.0  Hyderabad  50000.0
_____________________________________
    Name   Age       city   Salary
3  Sneha  25.0  Hyderabad  50000.0
4  kiran   NaN     Mumbai  35000.0
7  Meena  27.0     Mumbai  55000.0
_____________________________________
    Name   Age       city   Salary
0   Ravi  22.0  Hyderabad  30000.0
1  priya  24.0    Chennai  40000.0
3  Sneha  25.0  Hyderabad  50000.0
7  Meena  27.0     Mumbai  55000.0
    Name   Age       city   Salary
0   Ravi  22.0  Hyderabad  30000.0
1  priya  24.0    Chennai  40000.0
3  Sneha  25.0  Hyderabad  50000.0
7  Meena  27.0     Mumbai  55000.0

0    True
1    True
3    True
7    True
Name: Age, dtype: bool

In [77]:
import pandas as pd
emp_details = {
    "EmoID": [101, 102, 103, 104, 101],
    "City": ["Hyderabad", "Chennai", "Bangalore", None, "Hyderabad"],
    "Experience": [25, 30, None, 35, 25],
    "age":[25, 30, None, 35, 25]

}

df = pd.DataFrame(emp_details)
print(df)
df.isna()
df.isna().sum()
print
df.fillna({'City':'Unkown','Experience':0})
print(df)
df['age'] = df['age'].fillna(
    df['age'].median())
print(df)

df["salary"]= [1000, 2000, 3000, 4000, None]
print(df)
df["Bonus"]= df["salary"]*10/100
print(df)
df.drop(
    'Bonus',
    axis=1,
    inplace=True)
print(df)
#for multiple values
df.drop(
    columns=['salary'],
    inplace=True
)
df.loc[len(df)] = [109,'pune',4,25]
print(df)
df.drop(2,
        axis=0,
        inplace=True
        )
print(df)
#basix aggrigation & groupby &orderby

   EmoID       City  Experience   age
0    101  Hyderabad        25.0  25.0
1    102    Chennai        30.0  30.0
2    103  Bangalore         NaN   NaN
3    104       None        35.0  35.0
4    101  Hyderabad        25.0  25.0
   EmoID       City  Experience   age
0    101  Hyderabad        25.0  25.0
1    102    Chennai        30.0  30.0
2    103  Bangalore         NaN   NaN
3    104       None        35.0  35.0
4    101  Hyderabad        25.0  25.0
   EmoID       City  Experience   age
0    101  Hyderabad        25.0  25.0
1    102    Chennai        30.0  30.0
2    103  Bangalore         NaN  27.5
3    104       None        35.0  35.0
4    101  Hyderabad        25.0  25.0
   EmoID       City  Experience   age  salary
0    101  Hyderabad        25.0  25.0  1000.0
1    102    Chennai        30.0  30.0  2000.0
2    103  Bangalore         NaN  27.5  3000.0
3    104       None        35.0  35.0  4000.0
4    101  Hyderabad        25.0  25.0     NaN
   EmoID       City  Experience   age  salary  Bonus
0    101  Hyderabad        25.0  25.0  1000.0  100.0
1    102    Chennai        30.0  30.0  2000.0  200.0
2    103  Bangalore         NaN  27.5  3000.0  300.0
3    104       None        35.0  35.0  4000.0  400.0
4    101  Hyderabad        25.0  25.0     NaN    NaN
   EmoID       City  Experience   age  salary
0    101  Hyderabad        25.0  25.0  1000.0
1    102    Chennai        30.0  30.0  2000.0
2    103  Bangalore         NaN  27.5  3000.0
3    104       None        35.0  35.0  4000.0
4    101  Hyderabad        25.0  25.0     NaN
   EmoID       City  Experience   age
0    101  Hyderabad        25.0  25.0
1    102    Chennai        30.0  30.0
2    103  Bangalore         NaN  27.5
3    104       None        35.0  35.0
4    101  Hyderabad        25.0  25.0
5    109       pune         4.0  25.0
   EmoID       City  Experience   age
0    101  Hyderabad        25.0  25.0
1    102    Chennai        30.0  30.0
3    104       None        35.0  35.0
4    101  Hyderabad        25.0  25.0
5    109       pune         4.0  25.0

In [84]:
import pandas as pd
emp_details = {
    "EmoID": [101, 102, 103, 104, 101],
    "City": ["Hyderabad", "Chennai", "Bangalore", None, "Hyderabad"],
    "Experience": [25, 30, None, 35, 25],
    "age":[95, 30, None, 35, 25]

}

df = pd.DataFrame(emp_details)
print(df)
df.groupby('City')['age'].mean()

   EmoID       City  Experience   age
0    101  Hyderabad        25.0  95.0
1    102    Chennai        30.0  30.0
2    103  Bangalore         NaN   NaN
3    104       None        35.0  35.0
4    101  Hyderabad        25.0  25.0

City
Bangalore     NaN
Chennai      30.0
Hyderabad    60.0
Name: age, dtype: float64